"""Usage: python3 ci/icon/gen.py app/src/main/res <preview dir>

Generate the launcher icon (an open book wearing headphones: read or listen) as Android
vector drawables, plus SVG previews built from the same shapes."""
import os, sys

OUT_RES = sys.argv[1]          # app/src/main/res
OUT_PREVIEW = sys.argv[2]      # preview dir

def rrect(x, y, w, h, r):
    return (f"M{x+r},{y} h{w-2*r} a{r},{r} 0 0 1 {r},{r} v{h-2*r} a{r},{r} 0 0 1 {-r},{r} "
            f"h{-(w-2*r)} a{r},{r} 0 0 1 {-r},{-r} v{-(h-2*r)} a{r},{r} 0 0 1 {r},{-r} z")

BG_TOP, BG_BOTTOM = "#173B63", "#1F9E8A"   # night blue to the app's teal
COVER = "#FFB547"                          # the app's amber
PAGE, PAGE_SHADE = "#FFF8EC", "#F1E4CC"
INK = "#C9B48F"
CUP, PAD = "#FFFFFF", "#F29E2E"

# Shapes: (kind, path, colour, alpha, stroke width). The artwork is drawn on a 192 grid.
shapes = []
def fill(d, color, alpha=1.0): shapes.append(("fill", d, color, alpha, 0))
def stroke(d, color, width, alpha=1.0): shapes.append(("stroke", d, color, alpha, width))

# Soft shadow under the book.
fill("M40,146 C70,140 122,140 152,146 C122,152 70,152 40,146 Z", "#000000", 0.18)
# Amber cover peeking out under the pages.
fill("M96,98 C82,89 62,85 40,87 L40,141 C62,139 82,143 96,151 "
     "C110,143 130,139 152,141 L152,87 C130,85 110,89 96,98 Z", COVER)
# The pages, bowing up from the spine like an open book.
fill("M96,92 C83,83 64,79 46,81 L46,135 C64,133 83,137 96,145 Z", PAGE)
fill("M96,92 C109,83 128,79 146,81 L146,135 C128,133 109,137 96,145 Z", PAGE_SHADE)
stroke("M96,93 L96,144", "#D9C6A3", 2.4)
# Lines of text.
for i, y in enumerate([95, 105, 115, 125]):
    w = 0.8 if i == 3 else 1.0
    stroke(f"M{56},{y} C{66},{y - 2.5} {76},{y - 1.5} {56 + 30 * w},{y + 3}", INK, 3.2)
    stroke(f"M{136},{y} C{126},{y - 2.5} {116},{y - 1.5} {136 - 30 * w},{y + 3}", INK, 3.2)
# Headphones over the book: the band, then a cup on each side.
stroke("M48,104 C44,36 148,36 144,104", CUP, 10)
for x in (36, 138):
    fill(rrect(x, 90, 18, 34, 9), CUP)
    fill(rrect(x + 4.5, 95, 9, 24, 4.5), PAD)

GROUP = '<group android:pivotX="96" android:pivotY="96" android:scaleX="{s}" android:scaleY="{s}">'

def vector_path(kind, d, color, alpha, width, mono=False):
    if mono:
        color, alpha = "#FFFFFF", 1.0
    if kind == "fill":
        return f'        <path android:fillColor="{color}" android:fillAlpha="{alpha}" android:pathData="{d}" />'
    return (f'        <path android:strokeColor="{color}" android:strokeAlpha="{alpha}" android:strokeWidth="{width}" '
            f'android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{d}" />')

HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n{comment}\n'
          '<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra}\n'
          '    android:width="108dp" android:height="108dp" android:viewportWidth="192" android:viewportHeight="192">\n')

def write(name, text):
    path = os.path.join(OUT_RES, "drawable", name)
    with open(path, "w") as f:
        f.write(text)
    print("wrote", path)

SCALE = 0.92  # as big as fits: the cups stay inside the adaptive icon's safe circle

write("ic_launcher_foreground.xml",
      HEADER.format(comment="<!-- Launcher art: an open book wearing headphones. Generated by ci/icon/gen.py. -->", extra="")
      + "    " + GROUP.format(s=SCALE) + "\n"
      + "\n".join(vector_path(*s) for s in shapes) + "\n    </group>\n</vector>\n")

# Themed (monochrome) icon: the silhouette only, without the shadow and the lines of text.
mono = [s for s in shapes if s[2] not in ("#000000", INK, "#D9C6A3", PAD, PAGE_SHADE)]
write("ic_launcher_monochrome.xml",
      HEADER.format(comment="<!-- Themed-icon silhouette of the launcher art. Generated by ci/icon/gen.py. -->", extra="")
      + "    " + GROUP.format(s=SCALE) + "\n"
      + "\n".join(vector_path(*s, mono=True) for s in mono) + "\n    </group>\n</vector>\n")

write("ic_launcher_background.xml",
      HEADER.format(comment="<!-- Generated by ci/icon/gen.py. -->", extra='\n    xmlns:aapt="http://schemas.android.com/aapt"')
      + f'''    <path android:pathData="M0,0h192v192h-192z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="192" android:endY="192"
                android:startColor="{BG_TOP}" android:endColor="{BG_BOTTOM}" />
        </aapt:attr>
    </path>
    <path android:pathData="M16,80 a80,80 0 1,0 160,0 a80,80 0 1,0 -160,0 z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="96" android:centerY="80" android:gradientRadius="80"
                android:startColor="#3DFFFFFF" android:endColor="#00FFFFFF" />
        </aapt:attr>
    </path>
</vector>
''')

# ----- Previews: the icon in a circle, a squircle, and as a themed icon. -----
def svg_path(kind, d, color, alpha, width, mono=False):
    if mono:
        color, alpha = "#1F3B33", 1.0
    if kind == "fill":
        return f'<path fill="{color}" fill-opacity="{alpha}" d="{d}"/>'
    return (f'<path fill="none" stroke="{color}" stroke-opacity="{alpha}" stroke-width="{width}" '
            f'stroke-linecap="round" stroke-linejoin="round" d="{d}"/>')

def icon_svg(mask, themed=False):
    clip = {"circle": '<circle cx="96" cy="96" r="96"/>',
            "squircle": '<rect x="0" y="0" width="192" height="192" rx="54"/>'}[mask]
    if themed:
        bg = '<rect width="192" height="192" fill="#CFE8DF"/>'
        art = "".join(svg_path(*s, mono=True) for s in mono)
    else:
        bg = (f'<rect width="192" height="192" fill="url(#bg)"/>'
              f'<circle cx="96" cy="80" r="80" fill="url(#glow)"/>')
        art = "".join(svg_path(*s) for s in shapes)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192" width="192" height="192">'
            f'<defs><clipPath id="m">{clip}</clipPath>'
            f'<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG_TOP}"/>'
            f'<stop offset="1" stop-color="{BG_BOTTOM}"/></linearGradient>'
            f'<radialGradient id="glow" cx="0.5" cy="0.5" r="0.5"><stop offset="0" stop-color="#fff" stop-opacity="0.24"/>'
            f'<stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs>'
            f'<g clip-path="url(#m)">{bg}<g transform="translate(96 96) scale({SCALE}) translate(-96 -96)">{art}</g></g></svg>')

os.makedirs(OUT_PREVIEW, exist_ok=True)
for mask in ("circle", "squircle"):
    with open(os.path.join(OUT_PREVIEW, f"icon-{mask}.svg"), "w") as f:
        f.write(icon_svg(mask))
with open(os.path.join(OUT_PREVIEW, "icon-themed.svg"), "w") as f:
    f.write(icon_svg("circle", themed=True))
print("previews in", OUT_PREVIEW)
